services:
  - type: web
    name: climasphere
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
